class ComponentMakeTemplate {

  static Map<String, List<String>> makeOptions = {

    //Enclosure
    "Enclosure Serial No. 1": ["RITTAL"],
    "Enclosure Serial No. 2": ["RITTAL"],
    "Enclosure Serial No / Rev No": ["TRISHOOLIN", "OTHER"],

    // FAN BOX
    "Fan1": ["DELTA", "FANSTECH", "HICOOL"],
    "Fan2": ["DELTA", "FANSTECH", "HICOOL"],
    "Pan1": ["DELTA", "FANSTECH", "HICOOL"],

    "NTC8 – Fan1 – 10K": ["HONEYWELL", "VISHAY"],
    "NTC10 – Fan2 – 10K": ["HONEYWELL"],
    "NTC8 – Fan – 10K": ["HONEYWELL", "VISHAY"],

    // MAGNETICS
    "L1": ["SALZER", "CSE"],
    "L2": ["SALZER", "CSE"],
    "TR1": ["SALZER", "CSE"],
    "TR2": ["SALZER", "CSE"],
    "TR3": ["SALZER", "CSE"],
    "TR4": ["SALZER", "CSE"],
    "TR5": ["SALZER", "CSE"],
    "L1 (480uH/633A) - 1": ["SALZER", "CSE"],
    "L1 (480uH/633A) - 2": ["SALZER", "CSE"],
    "TV": ["SALZER", "CSE"],


    // SWITCHGEAR
    "CB01": ["ABB", "EATON", "LK", "SCHNEIDER", "C&S"],
    "CB02": ["ABB", "EATON", "LK", "SCHNEIDER", "C&S"],

    "K1": ["HIITIO", "GIGAVAC"],
    "K2": ["HIITIO", "GIGAVAC"],
    "K3": ["HONGFA", "GIGAVAC"],
    "K4": ["HIITIO", "GIGAVAC"],
    "K5": ["HIITIO", "GIGAVAC"],
    "K6": ["HONGFA", "GIGAVAC"],
    "K7": ["HIITIO", "GIGAVAC"],
    "K8": ["HIITIO", "GIGAVAC"],

    "KP1": ["HONGFA", "GIGAVAC"],
    "KP2": ["HONGFA", "GIGAVAC"],
    "KP3": ["HONGFA", "GIGAVAC"],
    "KP4": ["HONGFA", "GIGAVAC"],

    "T1A": ["HIITIO", "GIGAVAC"],
    "T1B": ["HIITIO", "GIGAVAC"],
    "T2A": ["HONGFA", "GIGAVAC"],
    "T2B": ["HIITIO", "GIGAVAC"],
    "T3A": ["HIITIO", "GIGAVAC"],
    "T6A": ["HONGFA", "GIGAVAC"],
    "T6B": ["HIITIO", "GIGAVAC"],
    "T3": ["HIITIO", "GIGAVAC"],
    "T4": ["HIITIO", "GIGAVAC"],
    "T5": ["HIITIO", "GIGAVAC"],
    "T7": ["HIITIO", "GIGAVAC"],
    "T8": ["HIITIO", "GIGAVAC"],

    "SPD3 – AC SPD": ["CITEL", "PHOENIX"],
    "SPD4 – AC SPD AUX": ["CITEL", "PHOENIX"],
    "SPD1 – DC SPD": ["CITEL", "PHOENIX"],
    "SPD2 – DC SPD": ["CITEL", "PHOENIX"],

    "FU1": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU2": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU3": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU4": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU5 – FU7": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FC1 – FU6": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU8 – FU9": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU10": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU11 – FU13": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU14 – FU16": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU17 – FU19": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU20 – FU22": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU23 – FU24": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],
    "FU25 – FU26": ["HOLLYLAND", "HIITIO", "LITTLEFUSE"],


    "FU1 (1500VDC)": ["HOLLYLAND", "HIITIO", "LITTLEFUSE", "EATON"],
    "FU2 (1500VDC)": ["HOLLYLAND", "HIITIO", "LITTLEFUSE", "EATON"],
    "FU4 (1250A 1500VDC)": ["HOLLYLAND", "HIITIO", "LITTLEFUSE", "EATON"],
    "FU8 (1250A 1500VDC)": ["HOLLYLAND", "HIITIO", "LITTLEFUSE", "EATON"],

    "ETH2 – ETH SWITCH": ["PHOENIX"],
    "QF1": ["CHINT", "ABB"],

    "CBF": ["SCHNEIDER", "CHINT"],
    "CBF1": ["SCHNEIDER"],
    "CBF2": ["SCHNEIDER"],
    "SW1": ["LK"],
    "SW2": ["LK"],


    // SENSORS
    "HCTU1": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTV1": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTW1": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTU2": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTV2": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTW2": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTU3": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTV3": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTW3": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTU4": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTV4": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTW4": ["LEM", "TAMURA", "SINOMAGS"],

    "HCTD1": ["LEM", "TAMURA", "SINOMAGS"],
    "HCTD2": ["LEM", "TAMURA", "SINOMAGS"],

    "HALL1": ["LEM", "TAMURA", "SINOMAGS"],
    "HALL2": ["LEM", "TAMURA", "SINOMAGS"],
    "HALL3": ["LEM", "TAMURA", "SINOMAGS"],
    "HALL4": ["LEM", "TAMURA", "SINOMAGS"],
    "HALL5": ["LEM", "TAMURA", "SINOMAGS"],

    // NTC
    "NTC7 – P1 – 10K": ["HONEYWELL"],
    "NTC9 – P2 – 10K": ["HONEYWELL"],

    "A8-1 PT Sensing Board": ["Newen V", "Newen A"],
    "A8-2 PT Sensing Board": ["Newen V", "Newen A"],

    // RESISTORS
    "RA18 – 66KΩ 100W": ["KWK", "RAATRONICS"],
    "RA19 – 66KΩ 100W": ["KWK", "RAATRONICS"],
    "RA20 – 66KΩ 100W": ["KWK", "RAATRONICS"],
    "RA21 – 80E 50W": ["KWK", "RAATRONICS"],
    "RA22 – 80E 50W": ["KWK", "RAATRONICS"],

    "RA1 – 80E 500W": ["KWK", "RAATRONICS"],
    "RA2 – 80E 500W": ["KWK", "RAATRONICS"],

    "RA3 – 33KΩ 100W": ["KWK", "RAATRONICS"],
    "RA4 – 33KΩ 100W": ["KWK", "RAATRONICS"],
    "RA5 – 33KΩ 100W": ["KWK", "RAATRONICS"],
    "RA6 – 33KΩ 100W": ["KWK", "RAATRONICS"],

    "RA15 – 66KΩ 100W": ["KWK", "RAATRONICS"],
    "RA16 – 66KΩ 100W": ["KWK", "RAATRONICS"],
    "RA17 – 66KΩ 100W": ["KWK", "RAATRONICS"],

    "RS1 (HEATER)": ["FINDER"],
    "HU1 (HUMIDISTAT)": ["FINDER"],
    "RS1": ["FINDER"],
    "RS2": ["FINDER"],
    "HU1": ["FINDER"],
    "HU2": ["FINDER"],
    "KT1": ["HONEYWELL"],
    "KT2": ["HONEYWELL"],
    "KT3": ["HONEYWELL"],
    "KT4": ["HONEYWELL"],
    "KT5": ["HONEYWELL"],
    "KT6": ["HONEYWELL"],
    "KT7": ["HONEYWELL"],
    "KT8": ["HONEYWELL"],
    "KT9": ["HONEYWELL"],
    "R1-R2 100E/150W": ["KWK", "RAATRONICS"],
    "R3-R14 7.5K/60W": ["KWK", "RAATRONICS"],
    "R15-10E/2W": ["KWK", "RAATRONICS"],
    "R16-100E/150W": ["KWK", "RAATRONICS"],
    "R17-100E/150W": ["KWK", "RAATRONICS"],

    "RA3 – RA8 – 100kΩ 50W": ["KWK", "RAATRONICS"],
    "RA9 – RA14 – 100kΩ 50W": ["KWK", "RAATRONICS"],
    "RA15 – RA17 – 60kΩ 50W": ["KWK", "RAATRONICS"],
    "RA18 – RA20 – 60kΩ 50W": ["KWK", "RAATRONICS"],

    // CAPACITORS
    "Cap Bank CF1": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank CF2": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank CF3": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank CF4": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank CF5": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank CF6": ["FARATRONIC", "TDK", "JIANGHAI"],
    "C1-C12": ["JIANGHAI", "TDK", "FARATRONICS", "CG ELECTRIC"],
    "C13-C24": ["JIANGHAI", "TDK", "FARATRONICS", "CG ELECTRIC"],
    "Cap Bank – CF1 – CF9": ["FARATRONIC", "TDK", "JIANGHAI"],
    "Cap Bank – CF10 – CF18": ["FARATRONIC", "TDK", "JIANGHAI"],


    // POWER SUPPLY
    "PS1 – 24V": ["MEANWELL"],
    "PS2 – 24V": ["MEANWELL"],
    "PS3 – 24V": ["MEANWELL"],
    "PS4 – 15V": ["MEANWELL"],
    "PS5 – 12V": ["MEANWELL"],
    "PS6 – 24V": ["MEANWELL"],
    "PS7 – 15V": ["MEANWELL"],
    "PS8 – +/-12V": ["MEANWELL"],
    "PS8 – ±12V": ["MEANWELL"],
    "PS9 – 24V": ["MEANWELL"],
    "PS10 – 15V": ["MEANWELL"],
    "PS11": ["MEANWELL"],
    "HMI": ["WEINTEK"],


    //PCB
    "A2-1 Interface Card": ['NEWEN'],
    "A3-1 Controller Card": ['NEWEN'],
    "A6-1 CB Card 1": ['NEWEN'],
    "A7-1 Gate Interlock Card": ['NEWEN'],
    "A7-2 Gate Interlock Card": ['NEWEN'],
    "A7-3 Gate Interlock Card": ['NEWEN'],
    "A12 AC Filter Card": ['NEWEN'],
    "A13-1 DC Filter": ['NEWEN'],
    "A1 Domain Controller": ['NEWEN'],
    "A2-2 Interface Card": ['NEWEN'],
    "A3-2 Controller Card": ['NEWEN'],
    "A3-3 Controller Card": ['NEWEN'],
    "A5 Power Supply ORing Card": ['NEWEN'],
    "A5-1 Power Supply ORing Card": ['NEWEN'],
    "A6-2 CB Card 2": ['NEWEN'],
    "A7-4 Gate Interlock Card": ['NEWEN'],
    "A7-5 Gate Interlock Card": ['NEWEN'],
    "A7-6 Gate Interlock Card": ['NEWEN'],
    "A10 SIM100": ['NEWEN'],
    "A11 Data Logger": ['NEWEN'],
    "A13-2 DC Filter": ['NEWEN'],

    "Controller (NI Board)": ["DYNAPOWER"],
    "A1: Domain controller": ["NEWEN"],
    "A2-1: Interface card": ["NEWEN"],
    "A2-2: Interface card": ["NEWEN"],
    "A3-1: Controller card": ["NEWEN"],
    "A3-2: Controller card": ["NEWEN"],
    "A3-3: Controller card": ["NEWEN"],
    "A5: Power Supply Oring card": ["NEWEN"],
    "A5-1: Power Supply Oring card": ["NEWEN"],
    "A6-1: ACB card": ["NEWEN"],
    "A6-2: ACB card": ["NEWEN"],
    "A7-1: Gate Interlock card": ["NEWEN"],
    "A7-2: Gate Interlock card": ["NEWEN"],
    "A7-3: Gate Interlock card": ["NEWEN"],
    "A7-4: Gate Interlock card": ["NEWEN"],
    "A7-5: Gate Interlock card": ["NEWEN"],
    "A7-6: Gate Interlock card": ["NEWEN"],
    "A10: SIM 100": ["NEWEN"],

    "DPS A1 - Interface Board": ["NEWEN"],
    "DPS A2 - Power Supply Board - 24VDC": ["NEWEN"],
    "DPS A3 - Power Supply Board - 15VDC": ["NEWEN"],
    "DPS A3-1 Power Supply Board - 15VDC": ["NEWEN"],
    "DPS IGBT Driver Board A4": ["NEWEN"],
    "DPS IGBT Driver Board A5": ["NEWEN"],
    "DPS IGBT Driver Board A6": ["NEWEN"],
    "DPS IGBT Driver Board A7": ["NEWEN"],
    "DPS A12 Fan Controller Board": ["NEWEN"],
    "DPS A13 Signal Detection and Power Transfer Board": ["NEWEN"],
    "DPS A14 Contactor Power Board": ["NEWEN"],

    "DPS Filter Board FL1": ["NEWEN"],
    "DPS Filter Board FL2": ["NEWEN"],
    "DPS Filter Board FL3": ["NEWEN"],
    "DPS Filter Board FL4": ["NEWEN"],
    "FILTER-5": ["SCHURTER"],

    // IGBT STACK ASSEMBLY
    "A4-1": ["NEWEN"],
    "A4-2": ["NEWEN"],
    "A4-3": ["NEWEN"],
    "A4-4": ["NEWEN"],
    "A4-5": ["NEWEN"],
    "A4-6": ["NEWEN"],
    "A4-7": ["NEWEN"],
    "A4-8": ["NEWEN"],
    "A4-9": ["NEWEN"],
    "A4-10": ["NEWEN"],
    "A4-11": ["NEWEN"],
    "A4-12": ["NEWEN"],

    "DPS IGBT Adaptor Board A8A-S1": ["NEWEN"],
    "DPS IGBT Adaptor Board A8B-S1": ["NEWEN"],
    "DPS IGBT Adaptor Board A8C-S1": ["NEWEN"],
    "DPS IGBT Adaptor Board A9A-S2": ["NEWEN"],
    "DPS IGBT Adaptor Board A9B-S2": ["NEWEN"],
    "DPS IGBT Adaptor Board A9C-S2": ["NEWEN"],
    "DPS IGBT Adaptor Board A10A-S3": ["NEWEN"],
    "DPS IGBT Adaptor Board A10B-S3": ["NEWEN"],
    "DPS IGBT Adaptor Board A10C-S3": ["NEWEN"],
    "DPS IGBT Adaptor Board A11A-S4": ["NEWEN"],
    "DPS IGBT Adaptor Board A11B-S4": ["NEWEN"],
    "DPS IGBT Adaptor Board A11C-S4": ["NEWEN"],

    "IGBT1": ["SEMIKRON"],
    "IGBT2": ["SEMIKRON"],
    "IGBT3": ["SEMIKRON"],
    "IGBT4": ["SEMIKRON"],
    "IGBT5": ["SEMIKRON"],
    "IGBT6": ["SEMIKRON"],
    "IGBT7": ["SEMIKRON"],
    "IGBT8": ["SEMIKRON"],
    "IGBT9": ["SEMIKRON"],
    "IGBT10": ["SEMIKRON"],
    "IGBT11": ["SEMIKRON"],
    "IGBT12": ["SEMIKRON"],
    "IGBT13": ["SEMIKRON"],
    "IGBT14": ["SEMIKRON"],
    "IGBT15": ["SEMIKRON"],
    "IGBT16": ["SEMIKRON"],
    "IGBT17": ["SEMIKRON"],
    "IGBT18": ["SEMIKRON"],
    "IGBT19": ["SEMIKRON"],
    "IGBT20": ["SEMIKRON"],
    "IGBT21": ["SEMIKRON"],
    "IGBT22": ["SEMIKRON"],
    "IGBT23": ["SEMIKRON"],
    "IGBT24": ["SEMIKRON"],

    "(IGBT) Q1-A": ["SEMIKRON"],
    "(IGBT) Q1-B": ["SEMIKRON"],
    "(IGBT) Q1-C": ["SEMIKRON"],
    "(IGBT) Q2-A": ["SEMIKRON"],
    "(IGBT) Q2-B": ["SEMIKRON"],
    "(IGBT) Q2-C": ["SEMIKRON"],
    "(IGBT) Q3-A": ["SEMIKRON"],
    "(IGBT) Q3-B": ["SEMIKRON"],
    "(IGBT) Q3-C": ["SEMIKRON"],
    "(IGBT) Q4-A": ["SEMIKRON"],
    "(IGBT) Q4-B": ["SEMIKRON"],
    "(IGBT) Q4-C": ["SEMIKRON"],

    "TS1 – 120°C": ["HONEYWELL"],
    "TS2 – 120°C": ["HONEYWELL"],
    "TS3 – 120°C": ["HONEYWELL"],
    "TS4 – 120°C": ["HONEYWELL"],
    "TS5 – 120°C": ["HONEYWELL"],
    "TS6 – 120°C": ["HONEYWELL"],
    "TS7 – 120°C": ["HONEYWELL"],
    "TS8 – 120°C": ["HONEYWELL"],
    "TS9 – 120°C": ["HONEYWELL"],
    "TS10 – 120°C": ["HONEYWELL"],
    "TS11 – 120°C": ["HONEYWELL"],
    "TS12 – 120°C": ["HONEYWELL"],

    "NTC1 – 10K": ["HONEYWELL"],
    "NTC2 – 10K": ["HONEYWELL"],
    "NTC3 – 10K": ["HONEYWELL"],
    "NTC4 – 10K": ["HONEYWELL"],
    "NTC5 – 10K": ["HONEYWELL"],
    "NTC6 – 10K": ["HONEYWELL"],

    "SKYPER1": ["SEMIKRON"],
    "SKYPER2": ["SEMIKRON"],
    "SKYPER3": ["SEMIKRON"],
    "SKYPER4": ["SEMIKRON"],
    "SKYPER1-U1": ["SEMIKRON"],
    "SKYPER2-U1": ["SEMIKRON"],
    "SKYPER3-U1": ["SEMIKRON"],
    "SKYPER4-U1": ["SEMIKRON"],
    "SKYPER1-V1": ["SEMIKRON"],
    "SKYPER2-V1": ["SEMIKRON"],
    "SKYPER3-V1": ["SEMIKRON"],
    "SKYPER4-V1": ["SEMIKRON"],
    "SKYPER1-W1": ["SEMIKRON"],
    "SKYPER2-W1": ["SEMIKRON"],
    "SKYPER3-W1": ["SEMIKRON"],
    "SKYPER4-W1": ["SEMIKRON"],
    "SKYPER1-U2": ["SEMIKRON"],
    "SKYPER2-U2": ["SEMIKRON"],
    "SKYPER3-U2": ["SEMIKRON"],
    "SKYPER4-U2": ["SEMIKRON"],
    "SKYPER1-V2": ["SEMIKRON"],
    "SKYPER2-V2": ["SEMIKRON"],
    "SKYPER3-V2": ["SEMIKRON"],
    "SKYPER4-V2": ["SEMIKRON"],
    "SKYPER1-W2": ["SEMIKRON"],
    "SKYPER2-W2": ["SEMIKRON"],
    "SKYPER3-W2": ["SEMIKRON"],
    "SKYPER4-W2": ["SEMIKRON"],

    "SKYPER 1-S1": ["SEMIKRON"],
    "SKYPER 2-S2": ["SEMIKRON"],
    "SKYPER 3-S3": ["SEMIKRON"],
    "SKYPER 4-S4": ["SEMIKRON"],

    "SKYPER 1 U1": ["SEMIKRON"],
    "SKYPER 2 U1": ["SEMIKRON"],
    "SKYPER 3 U1": ["SEMIKRON"],
    "SKYPER 4 U1": ["SEMIKRON"],
    "SKYPER 1 V1": ["SEMIKRON"],
    "SKYPER 2 V1": ["SEMIKRON"],
    "SKYPER 3 V1": ["SEMIKRON"],
    "SKYPER 4 V1": ["SEMIKRON"],
    "SKYPER 1 W1": ["SEMIKRON"],
    "SKYPER 2 W1": ["SEMIKRON"],
    "SKYPER 3 W1": ["SEMIKRON"],
    "SKYPER 4 W1": ["SEMIKRON"],
    "SKYPER 1 U2": ["SEMIKRON"],
    "SKYPER 2 U2": ["SEMIKRON"],
    "SKYPER 3 U2": ["SEMIKRON"],
    "SKYPER 4 U2": ["SEMIKRON"],
    "SKYPER 1 V2": ["SEMIKRON"],
    "SKYPER 2 V2": ["SEMIKRON"],
    "SKYPER 3 V2": ["SEMIKRON"],
    "SKYPER 4 V2": ["SEMIKRON"],
    "SKYPER 1 W2": ["SEMIKRON"],
    "SKYPER 2 W2": ["SEMIKRON"],
    "SKYPER 3 W2": ["SEMIKRON"],
    "SKYPER 4 W2": ["SEMIKRON"],

    "SKYPER 1": ["SEMIKRON"],
    "SKYPER 2": ["SEMIKRON"],
    "SKYPER 3": ["SEMIKRON"],
    "SKYPER 4": ["SEMIKRON"],

    "CD1-8": ["Faratronic", "Tdk"],
    "CD9-16": ["Faratronic", "Tdk"],
    "CD17-24": ["Faratronic", "Tdk"],
    "CD25-32": ["Faratronic", "Tdk"],
    "CD33-40": ["Faratronic", "Tdk"],
    "CD41-48": ["Faratronic", "Tdk"],

    "CD1 – CD6": ["FARATRONIC", "TDK"],
    "CD7 – CD14": ["FARATRONIC", "TDK"],
    "CD15 – CD21": ["FARATRONIC", "TDK"],
    "CD22 – CD28": ["FARATRONIC", "TDK"],
    "CD29 – CD35": ["FARATRONIC", "TDK"],
    "CD36 – CD42": ["FARATRONIC", "TDK"],

    "DIODE D1": ["IXYS"],
    "DIODE D2": ["IXYS"],
    "DIODE D3": ["IXYS"],
    "DIODE D4": ["IXYS"],

    "DS1, DS2 (Door Switch)": ["HONEYWELL"],
    "IS01 ISOMETER": ["BENDER"],
    "IS01 COUPLING": ["BENDER"]

  };

}
